daemon/containerdstore/prune.go
daemon/containerdstore/service.go

kNote: With the current containerd's pull behaviour the object that get
tagged as the pulled tag is not an image manifest but manifest list.
This means that doing:
```
docker pull docker.io/library/ubuntu:latest
docker tag docker.io/library/ubuntu:latest newrepo/ubuntu:latest
docker push newrepo/ubuntu:latest
```
Will result in an error, because the pull downloads only the default
platform and the newrepo/ubuntu:latest is a manifest list that
references all original image's platforms - and those cannot be pushed
to a remote because the pusher doesn't have them.
This will will work in case of single-platform manifest lists or if you
pull the manifest list along with all the platforms via ctr:
```
ctr --address /run/docker/containerd/containerd.sock -n moby \
image pull --all-platforms …
```

containerdstore: Initial push support

---

daemon/daemon.go
daemon/image_service.go
daemon/images/image_unix.go

Comes from [this PR](https://github.com/moby/moby/pull/43750)

Extract ImageService interface from the image service

---

daemon/containerd/progress.go
daemon/containerd/service.go

render `docker pull` progress
poll `content.Store` for active pulls and push`Progress` data according to moby's API

produce progress events polling ctrd's content.Store

---

daemon/oci_linux.go

This probably was a bad rebase in "Introduce containerd-snapshotter feature flag"

daemon: WithCommonOptions(): fix root initialisation

---

daemon/containerd/service.go

containerd: Implement push

---

daemon/containerd/progress.go
daemon/containerd/service.go

Follow up to:
- https://github.com/rumpl/moby/pull/15
Add progress for push. This shares code with pull progress and I extracted common things to other file to avoid cluttering service.go.

Push progress

---

daemon/containerd/prune.go
daemon/containerd/service.go

Initial implementation for `docker image prune` that doesn't handle any filters

daemon/containerd: Implement prune

---

daemon/containerd/service.go

This checks if the server that the user provided authentication for is the same as the server that we are actually authenticating with.

containerd/auth: Check if registry hostname matches

---

api/server/router/container/backend.go
api/server/router/container/inspect.go
daemon/cluster/executor/backend.go
daemon/cluster/executor/container/adapter.go
daemon/containerd/service.go
daemon/image_service.go
daemon/images/image_unix.go
daemon/images/image_windows.go
daemon/inspect.go
daemon/inspect_linux.go
daemon/inspect_windows.go
daemon/list.go
daemon/prune.go

implement GetContainerLayerSize using containerd snapshotter
container's RW layer (i.e active snapshot) size is available as a standard snapshotter API
container's virtual size isn't but can be computed as base image size (which we already have computation logic in place) + active snapshot size

compute container's layer size 

---

api/server/router/image/backend.go
api/server/router/image/image_routes.go
api/types/image/opts.go
daemon/cluster/executor/backend.go
daemon/cluster/executor/container/adapter.go
daemon/containerd/service.go
daemon/create.go
daemon/image_service.go
daemon/images/cache.go
daemon/images/image.go
daemon/images/image_builder.go
daemon/images/image_delete.go
daemon/images/image_events.go
daemon/images/image_history.go
daemon/images/image_pull.go
daemon/images/image_tag.go
daemon/images/images.go
daemon/list.go
daemon/oci_windows.go
image/image.go

Introduce GetImageWithDetails so that "image inspect" logic is not implement by router but backend, and we can re-implement using containerd snapshotter
relates to https://github.com/moby/moby/pull/43680

introduce GetImageWithDetails to manage image inspect data in backend

---

api/server/router/system/system_routes.go
daemon/containerd/service.go

implement `docker system df` - build cache is missing waiting for buildit to be plugged-in when containerd-snapshotter is enabled

docker system df

---

daemon/containerd/service.go
daemon/image_service.go
daemon/images/image_delete.go
daemon/images/image_exporter.go
daemon/images/image_import.go
daemon/images/image_pull.go
daemon/images/image_push.go
daemon/images/image_tag.go
daemon/images/service.go
image/events.go
image/tarexport/load.go
image/tarexport/save.go
image/tarexport/tarexport.go

Introduced ImageEventLogger with minimal dependencies to produce daemon events from a single place, and not have to include `LogImageEvent` in the image service interface

introduce ImageEventLogger to avoid duplicating logic in containerd_store

---

builder/builder-next/builder.go

Without this "docker build" fails with:
Error response from daemon: exporter "image" could not be found

Only use the image exporter in build if we don't use containerd

---

daemon/containerd/image_exporter.go
hack/make/.ensure-emptyfs
integration-cli/docker_cli_inspect_test.go

Fix `hack/make/.ensure-emptyfs` hanging because the emptyfs created has the deprecated v1 layout which is not supported by the containerd import.
Also changed the `load` behaviour to load all possible platforms from the archive - emptyfs is `linux/amd64`.

emptyfs: Use newer image layout

---

daemon/containerd/image_exporter.go

Follow-up to:
- https://github.com/rumpl/moby/pull/31
Changing `load` to import all platforms breaks the use case:
```
dockef pull busybox
docker save busybox > busybox.tar
docker load <busybox.tar
```
Because exporting the image (even with platform matcher) does export the whole manifest list referencing other platforms blobs (even if we don't have them).
Perhaps that's something that could be worked on upstream - for example adding the flag for `Import` to ignore importing the missing blobs? On the other hand the solution in this PR seems a bit better to me - because it feels wrong for the manifest in the archive to reference data it doesn't contain.
**- Description for …

containerd/save: Export only present platform manifests

---

daemon/containerd/service.go
daemon/disk_usage.go
daemon/start.go

This change fixes multiple things:
* pass ctx instead of nil because we need it while computing the layer
size
* don't return an error if the container is not found during the layer
size calculation, if a container is not found it means that it exited
* create the container with the image it was created from, the image is
used when computing the layer size

Fix `docker system df`

---

builder/builder-next/controller.go

Create moby builder with a special label to let buildx know we use containerd snapshotter and it can enable features accordingly

let buildx know we support containerd snapshotter

---

daemon/daemon.go

This needs more work to make containerd the source of truth when it's
used. It's safer for now to not try and restore any containers.

Don't try to restore containers on restart with contaienrd

---

builder/builder-next/builder.go
builder/builder-next/controller.go
cmd/dockerd/daemon.go

If buildkit uses a different snapshotter we can't list the images any
more because we can't find the snapshot.

Pass the current snapshotter to the buildkit worker

---

daemon/delete.go
daemon/start.go

Keeping the containerd's container around while our container is active makes `docker start` possible.
This is not really ideal, the best way to go about this would be to create the containerd container on create but this would change too much of the logic. Once we switch completely to containerd we can come back to this and change the logic.

Don't remove containerd's container after exit

---

daemon/daemon.go

After #51 the container creation fails:
<details>
<summary>Error spoiler</summary>
```
DEBU[2022-08-10T14:13:29.292797554Z] event published                               ns=moby topic=/snapshot/prepare type=containerd.events.SnapshotPrepare
2022/08/10 14:13:29 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 105 [running]:
net/http.(*conn).serve.func1()
/usr/local/go/src/net/http/server.go:1825 +0xb0
panic({0x21cea60, 0x3593260})
/usr/local/go/src/runtime/panic.go:844 +0x258
github.com/docker/docker/daemon.(*Daemon).updateContainerNetworkSettings(0x4000c1e240, 0x400020d400, 0x4000a83650)
/go/src/github.com/docker/docker/daemon/container_operations.go:468 +0xb8
github.com/docker/docker/daemon.(*Daemon).create(0x4000c1e240, {0x25334f0, …
```

daemon: Fix not initialized network controller

---

api/server/router/image/image_routes.go
daemon/containerd/image.go
daemon/images/image.go
image/image.go

we can't use referenceBackend when snapshotter is enabled
=> let GetImage lookup named reference for image when details are requested

GetImage to return image tags with details

---

api/server/router/container/backend.go
api/server/router/container/container_routes.go
daemon/containerd/image_exporter.go
daemon/containerd/service.go
daemon/daemon.go
daemon/export.go
daemon/image_service.go
daemon/images/image_exporter.go

removed GetLayerByID from from ImageService interface
replaced by add-hoc cast 
introduce `WithBaseFS` to implement container export

remove GetLayerByID from ImageService interface

---

builder/builder-next/controller.go

Currently, without special CNI config the builder would
only create host network containers that is a security issue.
Using runc directly instead of shim is faster as well
as builder doesn’t need anything from shim. The overhead
of setting up network sandbox is much slower of course.
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

builder-next: reenable runc executor

---

daemon/containerd/image_pull.go

c8d/pull: Don't unpack manually

---

daemon/config/config.go

This was added as part of rumpl/moby#40, but wasn't used.

daemon/config: remove unused DefaultContainerdSnapshotter

---

daemon/containerd/image.go
daemon/containerd/image_list.go
daemon/containerd/image_prune.go
daemon/containerd/service.go

Support the same filters as the non-c8d docker for `image prune -a`.
Also no longer remove the content from ContentStore ourselves - let c8d do that when deleting Image with SynchronousDelete (triggers GC immediately), and check afterwards which blobs are no longer in the store.
Not sure if there's anything meaningful from our side to do in `docker image prune`, as there is no dangling images in c8d due to GC. So currently the only sensible thing is to just trigger the GC, in case there were performed some actions without `SynchronousDelete` option.

c8d/prune: Handle filters, don't delete used images

---

daemon/containerd/mount.go
daemon/daemon.go
daemon/daemon_unix.go
daemon/image_service.go
daemon/images/mount.go

This fixes things that were broken due to nil BaseFS like `docker cp`
and running a container with workdir override.
This is more of a temporary hack than a real solution.
The correct fix would be to refactor the code to make BaseFS and LayerRW
an implementation detail of the old image store implementation and use
the temporary mounts for the c8d implementation instead.
That requires more work though.

c8d/daemon: Mount root and fill BaseFS

---

daemon/oci_linux.go

Some of the options need the client, WithUser for example.

Pass the containerd client when Applying oci options

---

cmd/dockerd/daemon.go
daemon/container.go
daemon/containerd/image.go
daemon/containerd/service.go
daemon/create.go
daemon/daemon.go
daemon/image_service.go
daemon/images/mount.go
daemon/images/service.go
daemon/info.go
daemon/oci_linux.go
daemon/start.go

- same as https://github.com/moby/moby/pull/43982
Make the function name more generic, as it's no longer used only for graphdrivers but also for snapshotters.
Make the ImageService the source of truth for the storage-driver that's used.
It was only used as an intermediate variable to store what's returned
by layerstore.DriverName() / ImageService.StorageDriver()

ImageService: rename GraphDriverName to StorageDriver, remove daemon.graphdriver

---

daemon/start.go

Make sure we keep the snapshotter that was set for the container
when starting it, instead of resetting it to the current daemon's
default.

daemon: containerStart() keep container's snapshotter

---

daemon/containerd/service.go
integration-cli/docker_cli_inspect_test.go
integration-cli/requirements_test.go

forward ports upstream changes from:
- second commit from https://github.com/moby/moby/pull/43983
- https://github.com/moby/moby/pull/44011
- relates to https://github.com/rumpl/moby/pull/31#discussion_r932522838

info: add driver-type, and add utility to check if snapshotters are enabled 

---

daemon/containerd/progress.go

Fix a bug which makes the progress handler never end if an error
happens before any ongoing is added.

c8d/progress: Fix progress not ending

---

daemon/containerd/image_commit.go

- relates to https://github.com/rumpl/moby/pull/40
- relates to https://github.com/rumpl/moby/pull/37

image commit: use configured snapshotter instead of default

---

daemon/containerd/image_push.go
daemon/containerd/store.go

This makes it possible to push multi-platform images if some contents are missing from the local content store, but can be fetched from a source repository.
The trick here is wrapping the ContentStore to return a fake `content.Info` with a `containerd.io/distribution.source.` label which specifies the source registry and repository for the blob. It's then used by the repository to cross-repo mount the blobs.
Caveats:
- Doesn't work with other registries than the one which provided the missing blob.
- Works only as long as we have a source manifest (it's deleted by `buildx purge -a` or restarting the daemon)
Test:
```bash
printf 'FROM alpine\nCMD ["echo", "hello"]' | docker buildx build . \
-t docker.io/repo/test:latest --platform linux/amd64,linux/arm64
docker push …
```

c8d/push: Push lazy blobs with distribution source labels

---

daemon/daemon.go

- relates to https://github.com/rumpl/moby/pull/77
see https://github.com/rumpl/moby/pull/77#issuecomment-1226092727
This is a temporary workaround for the daemon not yet having automatic
selection of snapshotters.

daemon: set containerd default snapshotter if none is configured

---

daemon/containerd/image_pull.go
daemon/containerd/image_push.go
daemon/containerd/lazy_push.go
daemon/containerd/progress.go

Follow up to:
- #74
Lazily fetch content that is needed for push.
Small content like manifests/indexes/configs are always fetched, as they can't be cross-repo mounted and they are small json files.
Other blobs are not fetched if the push registry matches the source registry - in such case they can be cross-repo mounted and there is no need to fetch them.
This makes the pull-tag-push workflow work:
```
docker pull busybox
docker tag busybox pawelgronowski465/mybusybox0830:latest
docker push pawelgronowski465/mybusybox0830:latest
```
It also works with other registries than Hub (HTTPS only), but in this case all content is fetched from the source registry and then pushed to the target registry.
The progress is currently a bit wonky as it doesn't show the correct status for the lazily …

c8d/push: Fetch missing resources that can't be mounted

---

daemon/containerd/progress.go

Related to:
- https://github.com/rumpl/moby/pull/73
Last progress update is performed with context that is already cancelled/done, so any operation accepting the context wasn't able to finish successfully.

c8d/progress: Don't use cancelled context

---

daemon/exec.go
daemon/exec_linux.go
daemon/exec_linux_test.go
daemon/exec_windows.go

Fixed exec when specifiying a user:
```
$ docker run -d --rm -it ubuntu /bin/bash 
fb183991d3b1a2fbcea9d97b49a01cfefd7869ca6a4d428cdd0843853468ec25
$ docker exec -u 1000 fb183991d3b1a2fbcea9d97b49a01cfefd7869ca6a4d428cdd0843853468ec25 id
uid=1000 gid=0(root) groups=0(root)
```
By getting the container from containerd and asking it to populate the spec with the right user.

Set the user on exec

---

daemon/containerd/resolver.go

httpfalback is responsible to retry access to insecure registry with plain HTTP, so it must detect incorrect response ent by registry to HTTPS request. As this takes place inside net/http/client we need to duplicate #send error detection

detect HTTP response to HTTPS request

---

daemon/containerd/image.go
daemon/containerd/image_tag.go

There were a lot of useless duplicated code
@thaJeztah we might want to change [the upstream PR](https://github.com/moby/moby/pull/43818) with the code from this PR

Refactor resolving/getting images

---

daemon/containerd/image.go
image/image.go

Created a new function in the `image` package to be able to create an image with a given ID, this is needed because the image id is read-only and created by the image store on image creation. We no longer use the image store with containerd and need a way to return an image with its ID.
With this change k8s on Desktop works
```
$ docker pull hello-world
$ docker inspect hello-world
```
The inspect JSON should have an ID that is not empty

Return the image ID on inspect

---

daemon/containerd/image_changes.go
daemon/exec_linux.go
daemon/oci_linux.go
oci/oci.go

Mounting the same directory twice with overlayfs will put the mounts in an undefined behavior. We need to make sure that the mounts we do are read-only.
Took the code from containerd and added the `ReadonlyMounts` method to make sure that we are mounting in read-only mode.
* copy/paste c8d code from https://github.com/containerd/containerd/blob/main/oci/spec_opts.go
* https://github.com/moby/buildkit/pull/1100
Run `docker run -it --user 1000 docker/dev-environments-go:stable-1` and then, in a different terminal, exec into that container, try to create a file, it should work and not fail with `No such file or directory`.

Make sure the mount is readonly when searching for a user/group

---

daemon/containerd/image.go

This align with API Client: 
when image both has tag and digest, only digest is considered and tag is dropped
see https://github.com/rumpl/moby/blob/master/client/image_pull.go#L55-L63

consider digest and ignore tag when both are set

---

daemon/containerd/image_list.go

This allows `ImageList` AP to return familiar image names (without `docker.io/library` registry/repository prefix)
While docker CLI do familiarize reference, Docker Desktop UI doesn't

image ls to return familiar names

---

daemon/containerd/image_exporter.go

The image was scheduled for deletion before the actual export was started.
For bigger images this resulted in the output archive being incomplete, because the content is usually deleted faster than the whole image is exported to an archive.
Also made the temporary image name unique by adding an uuid, just to avoid breaking the export if concurrent exports are taking place.

c8d/export: Fix temporary image being deleted too early

---

builder/builder-next/control/control.go
builder/builder-next/exporter/containerimage/export.go
daemon/containerd/image.go
daemon/containerd/image_list.go

Requires:
- #99
Set the `dangling-name-prefix` attribute to `dangling` to store images that are built without a tag.
Image list was also adjusted to account for the dangling images and they are shown like in the current Docker.

c8d/builder: store untagged images

---

daemon/containerd/image_prune.go
daemon/containerd/image_tag.go

Requires:
- https://github.com/rumpl/moby/pull/100
Changes:
- `docker image prune` deletes dangling (images which were built without a tag) images
- `docker tag <dangling hash> <new-tag>` will remove the old "dangling" image so `docker image ls` will show only the image with a <new-tag>

Handle dangling images in prune/tag

---

daemon/images/mount.go

Relates to:
- https://github.com/rumpl/moby/pull/65
#65 did introduce unsetting the BaseFS, which is actually incorrect behaviour: https://github.com/moby/moby/pull/44075#discussion_r968123380 and breaks `docker run` when running with the old graphdriver instead of c8d snapshotter.
This reverts part of #65, so when upstreaming, this needs to be squashed.

daemon/images: Don't unset BaseFS

---

daemon/start.go

daemon/start: Restore TODO context for container.Start

---

builder/builder-next/worker/containerdworker.go
builder/dockerfile/dispatchers_test.go
daemon/containerd/image.go
daemon/containerd/image_commit.go
daemon/images/image_import.go
daemon/images/image_tag.go
daemon/oci_linux.go
oci/oci.go

Fix linter errors that were made in our fork's and were detected after rebase on upstream master.
Each commit from this PR should be squashed to the corresponding commit it fixes when doing the next rebase or when upstreaming.

Fix linter errors after rebase

---

api/types/container/config.go
daemon/daemon.go

Re-enable the containers restore mechanism after daemon restart.
This seems to work correctly after bringing up Cory's libcontainerd related changes from the upstream.

c8d/daemon: Allow restore containers

---

daemon/containerd/image.go
daemon/containerd/image_commit.go

This fixes a few bugs in the `docker commit`.
- Committing an image from container running a non-native platform produced an image for the native platform
- If the base image was manifest list, then the resulting image was missing the parent's rootfs in its layers
- Usage of docker/errdefs instead of containerd/errdefs for checking containerd not found error
- Two images being saved after commit (one with the desired name, and the other one with digest).

c8d/commit: Fix choosing base manifest, set dangling name, fix errdefs

---

.github/workflows/buildkit.yml

Buildkit tests were failing due to hash mismatch of the url `https://raw.githubusercontent.com/moby/moby/master/README.md`
which was expected to have the content of `https://raw.githubusercontent.com/moby/moby/v20.10.21/README.md`.
Latest tagged version didn't include a fix for this, so let's set a buildkit revision used for tests to one that includes this fix:
https://github.com/moby/buildkit/pull/3281

Fix buildkit tests

---

daemon/containerd/image_exporter.go

This fixes the `docker index sbom --image <image-or-shortid> --output ./sbom`
Previously, `manifest.json` (which made the archive backwards compatible
with Docker image archive) was generated only if exported image was a
single platform manifest. Containerd selects only one manifest as the
`manifest.json`, so let's hint it to choose the default platform.
This makes the output archive compatible with both OCI format (which
allows to import all platforms) and Docker image which will import only
the platform it was exported from.
Also added support for short-ids.

c8d/save: Short ids, make sure manifest.json is generated

---

daemon/containerd/image_changes.go
daemon/list.go

- `docker ps` no longer crashes when running a container with non-default platform
- `docker diff` works for containers with non-default platform

Fix references to default platforms in ps and diff

---

daemon/containerd/image.go

It's horrible, but some clients (such as the docker 17.03 CLI used in CI) still perform string-matching to detect that the *image* wasn't found. This requires the error to be prefixed with "No such image:". Without this prefix, the CLI prints the error message, and exits.
Before this:
docker run -it --rm hello-world
docker: Error response from daemon: id not found.
See 'docker run --help'.
After this:
docker run -it --rm hello-world
Unable to find image 'hello-world:latest' locally
faa03e786c97: Download complete
...

daemon/containerd: fix compat for "docker run" with image that's not present

---

builder/builder-next/builder.go

This fixes `docker build --quiet` not outputting image ID when containerd image store is enabled, as it uses `image` exporter.

builder: Emit image id when using image exporter

---

daemon/containerd/image_list.go

Fixup for:
- https://github.com/rumpl/moby/pull/113
Without this, dangling images are not visible in the `docker image ls` output.
This just restores behaviour introduced in ab6918735dbaf77df716b779dd6c01fff4c1f2e3 and accidentally removed in recent PR which introduced changes in image listing.

c8d/list: Make dangling images parseable by the cli

---

api/server/router/image/backend.go
api/server/router/image/image_routes.go
daemon/containerd/image_import.go
daemon/image_service.go
daemon/images/image_import.go

Same as:
- https://github.com/moby/moby/pull/44628
Implemented `docker import` for containerd integration
Write the blob to the content store, calculate the uncompressed data digest and create a manifest and image config for the selected platform (default is host platform if none provided).
I also extracted the common logic (parsing image name into reference and getting a data stream) to the API routes.
1. Export some image from non-c8d Docker
```bash
$ docker run --name asdf ubuntu sh -c 'apt-get -y update && apt-get install -y fish'
$ docker export asdf >asdf.tar
```
2. Import it in the c8d Docker
```bash
$ docker import asdf.tar asdf
sha256:149082be8a52c73586a13399a03947535ef6ba84925b139fe788695f843945b2
$ # Compressed archives …
```

daemon/c8d: Implement import

---

daemon/list.go

Check for generic `errdefs.NotFound` rather than specific error helper struct when checking if the error is caused by the image not being present.
It still works for `ErrImageDoesNotExist` because it implements the NotFound errdefs interface too.

daemon: Replace ErrImageDoesNotExist typecheck

---

daemon/containerd/service.go

We don't support these settings yet and this is used when reload daemon configuration.
This fixes pinata e2e tests which modify the configuration and then reload the daemon.

c8d: Don't panic in UpdateConfig
