rumpl/moby

daemon/daemon.go
daemon/oci_linux.go

Copied the code from https://github.com/moby/moby/pull/43735

Introduce containerd-snapshotter feature flag

---

cmd/dockerd/daemon.go
daemon/containerd/service.go
daemon/daemon.go
daemon/oci_linux.go

Initial pull/ls works
Build is deactivated if the feature is active

Create the containerd image service

---

daemon/containerd/service.go

Compute image VirtualSize as the sum of all layers disk usage
inspired by https://github.com/containerd/nerdctl/blob/afee9a509a30fb965e0490ebb0c418f7241c0750/cmd/nerdctl/images.go#L362

Compute image VirtualSize

---

daemon/containerd/service.go

Made pull work with repos that need authorization
Use authConfig to create DockerAuthorizer which provides stored credentials

containerd/pull: Use authorization

---

api/server/router/image/backend.go
api/server/router/image/image_routes.go
daemon/containerd/service.go
daemon/image_service.go
daemon/images/image_delete.go
daemon/images/image_prune.go

Implemented image deletion for containerd

Implement ImageDelete for containerd

---

api/server/router/image/backend.go
api/server/router/image/image_routes.go
daemon/containerd/service.go
daemon/image_service.go
daemon/images/image_exporter.go

Add support for docker image load/save

Implement load/save

---

daemon/containerd/service.go

Importing an image doesn't unpack it, which breaks the `docker image ls` when it tries to calculate the size:
```
Error response from daemon: snapshot sha256:13e8c0db60e709f432236af8ef51cbc5f4e8e871eb34bb0a22c1b91abd7d8dd7 does not exist: not found
```

containerd: Unpack loaded images

---

daemon/containerd/service.go

compute "shared size" by counting snapshots usage while listing images
to be addressed: I'm not sure how this should interact with filters: shall we count as "shared" some layers that are excluded, based on selected filters, or are those metrics "within the scope of the filter" ?

compute image's shared size

---

daemon/containerd/service.go

remove obsolete func `LookupImage`

remove obsolete LookupImage

---

daemon/containerd/image_exporter.go

c8d/exporter: Use configured snapshotter instead of default

---

daemon/create.go
daemon/delete.go

With a lease we make sure that containerd won't garbage collect out
snapshot. We remove the lease when the container is removed and leave it
to containerd to clean things up.

Create a lease for the snapshots we prepare

---

daemon/containerd/image_delete.go

This makes it possible to delete an image by name or id

Use getImage() to get the image when deleting

---

daemon/containerd/image.go

With this change `docker run -d -P nginx` correctly assigns a random port the container

Add ExposedPorts and Volumes to the image returned

---

daemon/containerd/image_pull.go
daemon/containerd/image_push.go
daemon/containerd/resolver.go
daemon/containerd/service.go
daemon/daemon.go
registry/service.go

see https://github.com/rumpl/moby/pull/81
This fix ability to pull images from an insecure registry, and support for hubproxy in Docker Desktop to run kubernetes

C8d resolver hosts

---

api/types/container/config.go
daemon/containerd/image.go
daemon/containerd/image_changes.go
daemon/containerd/image_commit.go
daemon/containerd/image_delete.go
daemon/containerd/image_history.go
daemon/containerd/image_tag.go
daemon/create.go
daemon/start.go

introduce ability to select platform for image being ran

docker run --platform

---

daemon/containerd/image_list.go
daemon/containerd/image_prune.go

Use containerd's filters to implement `image ls --filter` where feasible

delegate filtering to containerd where possible

---

daemon/delete.go

daemon: Fix nil dereference on c8d container deletion

---

daemon/containerd/image.go

Including buildkit's custom properties

Add missing properties to the image

---

.github/workflows/buildkit.yml

- backports https://github.com/moby/moby/pull/44571
- relates to https://github.com/moby/buildkit/pull/3353
- fixes https://github.com/moby/moby/issues/44570
(cherry picked from commit 381fa4afcae723de811b1bd1c330a5ad4a8d5952)

[c8d] ci(buildkit): update buildkit ref to fix issue with alpine image

---

daemon/containerd/image_tag.go

Downstream https://github.com/moby/moby/pull/44781 :D

Fix tagging when image already exists

---

daemon/containerd/image_list.go

Implements `dangling` filter, which has been mentioned a lot in customer feedbacks.

c8d/list: Support dangling image filter

---

api/server/router/image/image_routes.go
daemon/containerd/image_list.go
daemon/images/image_list.go

- Backports: https://github.com/moby/moby/pull/44840

list: Backport changes from upstream
